apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: artifactoryproinstances.artifactory.operator.k8s.trask.cz
spec:
  group: artifactory.operator.k8s.trask.cz
  names:
    kind: ArtifactoryProInstance
    listKind: ArtifactoryProInstanceList
    singular: artifactoryproinstance
    plural: artifactoryproinstances
    shortNames:
      - artifpro
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
