kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: artifactory-operator
subjects:
  - kind: ServiceAccount
    name: artifactory-operator
    namespace: artifactory-operator
roleRef:
  kind: ClusterRole
  name: artifactory-operator
  apiGroup: rbac.authorization.k8s.io
