apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: artifactory-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - artifactory-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
# Manages custom resources
- apiGroups:
  - artifactory.operator.k8s.trask.cz
  resources:
  - '*'
  verbs:
  - '*'
# Adds events
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
